@@ -0,0 +1,10 @@
CXX = g++
CXXFLAGS = -Wall -g

CiffCaffParser: CiffCaffParser.o
	$(CXX) $(CXXFLAGS) -o CiffCaffParser CiffCaffParser.o

# The main.o target can be written more simply

CiffCaffParser.o: CiffCaffParser.cpp
	$(CXX) $(CXXFLAGS) -c CiffCaffParser.cpp
